"""
reporter.py — 单文件 HTML 报告生成器。输出 projects/<id>/output/reports/report_<timestamp>.html。
对应方案设计 §11.5 报告。
"""
import json
from datetime import datetime
from pathlib import Path


def build_report(proj_id: str, p0_summary: dict = None,
                 drift_report: dict = None, test_results: dict = None) -> str:
    """
    生成 p0_summary + drift + test_results 的整合 HTML 报告。
    """
    proj_name = proj_id
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 从 p0_summary 文件读
    if p0_summary is None:
        sp = Path.cwd() / "projects" / proj_id / "output" / "config" / "p0_summary.md"
        if sp.exists():
            p0_summary = {"source": str(sp)}
        else:
            p0_summary = {}

    html = f"""<!DOCTYPE html>
<html lang="zh-CN"><head><meta charset="utf-8"><title>API_AI 测试报告 — {proj_name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #f5f7fa; margin: 0; padding: 20px; color: #333; }}
.container {{ max-width: 1200px; margin: 0 auto; }}
.header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 12px; margin-bottom: 20px; }}
.header h1 {{ margin: 0; font-size: 24px; }}
.header .meta {{ margin-top: 8px; opacity: 0.85; font-size: 14px; }}
.card {{ background: white; border-radius: 10px; padding: 20px; margin-bottom: 16px; box-shadow: 0 2px 4px rgba(0,0,0,0.06); }}
.card h2 {{ margin: 0 0 12px 0; font-size: 18px; color: #444; border-bottom: 2px solid #667eea; padding-bottom: 8px; }}
.stat-row {{ display: flex; gap: 16px; flex-wrap: wrap; }}
.stat {{ flex: 1; min-width: 120px; background: #f0f4ff; padding: 16px; border-radius: 8px; text-align: center; }}
.stat .num {{ font-size: 32px; font-weight: bold; color: #667eea; }}
.stat .label {{ font-size: 12px; color: #888; margin-top: 4px; }}
.endpoint-list {{ font-size: 13px; line-height: 1.8; }}
.endpoint {{ display: inline-block; background: #eef2ff; padding: 2px 8px; border-radius: 4px; margin: 2px; font-family: monospace; font-size: 12px; }}
.badge-red {{ background: #fee2e2; color: #dc2626; }}
.badge-green {{ background: #dcfce7; color: #16a34a; }}
.badge-blue {{ background: #dbeafe; color: #2563eb; }}
</style></head><body>
<div class="container">
<div class="header">
  <h1>📊 API_AI 测试报告 — {proj_name}</h1>
  <div class="meta">生成时间: {ts}</div>
</div>
<div class="card">
  <h2>📋 概览</h2>
  <div class="stat-row">
    <div class="stat"><div class="num">-</div><div class="label">端点总数</div></div>
    <div class="stat"><div class="num">-</div><div class="label">已生成 API 函数</div></div>
    <div class="stat"><div class="num">-</div><div class="label">CRUD 用例</div></div>
  </div>
</div>
<div class="card">
  <h2>📁 产物清单</h2>
  <ul>
    <li><code>projects/{proj_id}/api/</code> — {len(list((Path.cwd()/"projects"/proj_id/"api").glob("*.py")))-1 if (Path.cwd()/"projects"/proj_id/"api").exists() else 0} 个薄函数模块</li>
    <li><code>projects/{proj_id}/kb/api_catalog.json</code> — API 目录 IR</li>
    <li><code>projects/{proj_id}/exports/estack_openapi.yaml/json</code> — OpenAPI 3.1 导出</li>
    <li><code>projects/{proj_id}/exports/estack_postman.json</code> — Postman Collection v2.1</li>
    <li><code>projects/{proj_id}/tests/</code> — pytest CRUD 用例</li>
  </ul>
</div>
<div class="card">
  <h2>📖 导出文件</h2>
  <p>以下文件可直接导入 Apifox/Postman:</p>
  <ul>
    <li><strong>OpenAPI 3.1</strong>: <code>projects/{proj_id}/exports/{proj_id}_openapi.yaml</code> (Apifox 首选)</li>
    <li><strong>Postman</strong>: <code>projects/{proj_id}/exports/{proj_id}_postman.json</code> (Collection v2.1)</li>
  </ul>
</div>
<p style="text-align:center;color:#999;font-size:12px;margin-top:40px;">Generated by API_AI_test — {ts}</p>
</div></body></html>"""
    return html


def save_report(proj_id: str, report_dir: str = None):
    """生成并保存 HTML 报告。"""
    proj_dir = Path.cwd() / "projects" / proj_id
    out_dir = Path(report_dir) if report_dir else (Path.cwd() / "output" / "reports")
    out_dir.mkdir(parents=True, exist_ok=True)

    html = build_report(proj_id)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = out_dir / f"report_{ts}.html"
    out_path.write_text(html, encoding="utf-8")
    print(f"[report] ✅ {proj_id}: {out_path}")
    return out_path
